
name: Complete Workflow

on: ['push']

jobs: 

  build: 

    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [12.x]

    steps: 
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow 

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Start DB
      uses: harmon758/postgresql-action@v1
      with: 
        postgresql version: '12.4'
        postgresql password: docker
        postgresql user: postgres
        postgresql db: booksmart

    - name: Install dependencies
      run: npm ci

    - name: Run all tests
      run: npm run test

     - shell: bash
      if: github.ref == 'refs/heads/master'
      name: Create SSH deployment key
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: ./scripts/deploy.sh

    - name: Deployment
      if: github.ref == 'refs/heads/master'
      run: git remote add umbler ssh://git@geonosis.deploy.umbler.com:9922/j5r30dgk/gustavo-booksmart-com.git && git push umbler master
      env:
        CI: true
